### PR TITLE
view counties

### PR DESCRIPTION
**Pull request by varughese**

### CODE REVIEW

**Comment by Richie78321** [comment]
Dope thanks for this -- I have a couple nits that I'll be working on for a bit

**Comment by varughese** [comment]
Yeah edit my branch and make any changes

**Comment by Richie78321** [comment]
@Zmwang622 I can't see why this is failing

**Comment by Richie78321** [comment]
I've fixed most of my nits. When Ming is able to check to Vercel build logs I can fix it up and we can deploy

**Pull request merged**
