### PR TITLE
Add media section to homepage

### PR DESCRIPTION
**Pull request by GideonShils**
Added a media section with 5 headlines:

Screen Shot 2021-02-09 at 12 44 51 AM

### CODE REVIEW

**Comment by Richie78321** [comment]
Nice work! I'm thinking we should probably make use of [NextJS image optimization](https://nextjs.org/docs/api-reference/next/image) to ensure this page loads quickly for everyone. Other than that, looks great!

**Comment by GideonShils** [comment]
@Richie78321 ah cool, I haven't used next.js before so was unaware of this. I'll update later today

**Comment by Richie78321** [comment]
@GideonShils Awesome, thanks! I haven't used it before either, but I took a shot at changing it and it seems a bit finnicky with the way the styling is currently set up. Lmk if you run into any trouble.

**Comment by GideonShils** [comment]
Hey @Richie78321, just updated to use the `<Image />` element

**Review by Richie78321 — APPROVED** [review]
This looks great. I'm going to make a few changes but otherwise it should be live soon!

**Comment by GideonShils** [comment]
Ayo @Richie78321, did this get deployed? Not seeing live

**Comment by Richie78321** [comment]
Hey @GideonShils sorry this is taking so long. There are a few changes that need to be made before this can be deployed, and a bunch of volunteer onboarding stuff came up this week so this got kind of pushed aside. Once I get a moment (likely this weekend) you should see it on the live site. Thanks again so much for helping out with this!

**Comment by GideonShils** [comment]
@Richie78321 no worries, lemme know via code review if there are any changes I can make on my end and happy to push up some new commits.

**Comment by Richie78321** [comment]
@GideonShils Deployed!

**Pull request merged**
